services:

  nginx:
    restart: unless-stopped

  app:
    restart: unless-stopped

  reverb:
    restart: unless-stopped
      
  mariadb:
    restart: unless-stopped

  redis:
    restart: unless-stopped